apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: attempt-history-service-api-hpa
  namespace: peerprep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: attempt-history-service-room-event-consumer-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
