version: '3'
services:
  attempt_history_service_database:
    image: postgres:16-bookworm
    networks:
      - peerprep
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped

  attempt_history_service_database_initialiser:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_attempt_history_service_database_initialiser
    build:
      context: .
      dockerfile: ./dockerfiles/database_initialiser.dockerfile
    networks:
      - peerprep
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: attempt_history_service_database
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: ${DATABASE_SHOULD_USE_TLS}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}
      SHOULD_FORCE_INITIALISATION: ${SHOULD_FORCE_INITIALISATION}
    depends_on:
      - attempt_history_service_database
    restart: on-failure

  attempt_history_service_api:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_attempt_history_service_api
    build:
      context: .
      dockerfile: ./dockerfiles/api.dockerfile
    networks:
      - peerprep
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: attempt_history_service_database
      DATABASE_PORT: 5432
      DATABASE_SHOULD_USE_TLS: ${DATABASE_SHOULD_USE_TLS}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_CONNECTION_TIMEOUT_MILLIS: ${DATABASE_CONNECTION_TIMEOUT_MILLIS}
      DATABASE_MAX_CLIENT_COUNT: ${DATABASE_MAX_CLIENT_COUNT}

      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}

      API_PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - attempt_history_service_database
    restart: unless-stopped

  attempt_history_service_mq_consumer:
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_attempt_history_service_mq_consumer
    build:
      context: .
      dockerfile: ./dockerfiles/mq_consumer.dockerfile
    networks:
      - peerprep
    environment:
      API_HOST: attempt_history_service_api
      API_PORT: ${API_PORT}

      ROOM_SERVICE_MQ_USER: ${ROOM_SERVICE_MQ_USER}
      ROOM_SERVICE_MQ_PASSWORD: ${ROOM_SERVICE_MQ_PASSWORD}
      ROOM_SERVICE_MQ_HOST: ${ROOM_SERVICE_MQ_HOST}
      ROOM_SERVICE_MQ_PORT: ${ROOM_SERVICE_MQ_PORT}
      ROOM_SERVICE_MQ_VHOST: ${ROOM_SERVICE_MQ_VHOST}
      ROOM_SERVICE_MQ_SHOULD_USE_TLS: ${ROOM_SERVICE_MQ_SHOULD_USE_TLS}
      ROOM_SERVICE_MQ_EXCHANGE_NAME: ${ROOM_SERVICE_MQ_EXCHANGE_NAME}
      ROOM_SERVICE_MQ_QUEUE_NAME: ${ROOM_SERVICE_MQ_QUEUE_NAME}

      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}

      DOC_SERVICE_HOST: ${DOC_SERVICE_HOST}
      DOC_SERVICE_PORT: ${DOC_SERVICE_PORT}
    depends_on:
      - attempt_history_service_api
    restart: unless-stopped

networks:
  peerprep:
    external: true
    name: peerprep
