apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: attempt-history-service-database-client-secret
  namespace: peerprep
spec:
  encryptedData:
    database-password: AgCm2AubQRBa6FfAjWu3yfsrUtlbvUlbYywsZZ1/6ulShVh+dbx1/89Awzpu9MXhodgjp3D8UlKzwDXwkKsz9pVNccKjW3+bzHW9wFyfcn5pG+hnWnvqGHekIbR39fJYimFbUznBRbGMNkXKGXJOapftE3w1JFHFxTLVF3DjTGbFhxLXaO5hTX29ahBLph1R07yELcuhSpM+xodm6KB1BiK53i9Cg1+LVmSU2rDkHkq7AGnhi4MSKlmZncU9jg6aCH2y3FkC67GZl30fojhhROW8mxcfryyN25Iy0cTRkXETMS/1UOrbM2MWRI2+Z0AkZVweadNLKeZaJ4rMv1qhyRzItDQkSIMp4XI1APSfd3wjD4K7Cu+CUg6Ue1psYy6v9d1EGEP10LsEzYlrxMlnbcQ7T7q2HDc2gvAKRuLItay7VpnbddjX+rmIAVAJBCEdo1mqqWgHLFrAfCz69PStEa9l1UeeJOxPbS616Num9uTfHOrGHqv8jpRddUnOtRsggacaE6wxm8EkySZztTo/CczJZeTLRaLWwerCQE9vnfrRSNquRr6aCckw4B0+q/yjsRLPMTwoW/DRMrHHce81uX+bX1JRNw2JE+8ZWZrP61PFoFatHmQugGxpe0ZpApy3KehLdc3uUIssIP7U7dTYPYhVa68xsGP2vBvmqhejIlyXyOzbuy4QCF15+Azez7nt85N13xy1Y6K2kpRsJl5/V4HyuOwLkBMmeYcNrRM7tQ7eJQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: attempt-history-service-database-client-secret
      namespace: peerprep
    type: Opaque

