apiVersion: v1
kind: ConfigMap
metadata:
  name: attempt-history-service-database-client-config-map
  namespace: peerprep
data:
  database-user: djodqnjc
  database-host: kiouni.db.elephantsql.com
  database-port: '5432'
  database-should-use-tls: 'true'
  database-name: djodqnjc
  database-connection-timeout-millis: '0'
  database-max-client-count: '20'
