FROM node:lts-hydrogen

COPY ./build /peerprep_attempt_service_api/
COPY package.json /peerprep_attempt_service_api/

WORKDIR /peerprep_attempt_service_api

RUN npm install --omit=dev -y

CMD node main.js
