apiVersion: apps/v1
kind: Deployment
metadata:
  name: attempt-history-service-api-deployment
  namespace: peerprep
  labels:
    app: attempt-history-service-api
spec:
  selector:
    matchLabels:
      app: attempt-history-service-api
  template:
    metadata:
      namespace: peerprep
      labels:
        app: attempt-history-service-api
    spec:
      containers:
        - name: attempt-history-service-api
          image: ghcr.io/cs3219-ay2324s1-g04/peerprep_attempt_history_service_api
          ports:
            - containerPort: 9006
          env:
            - name: AHS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-user
            - name: AHS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: attempt-history-service-database-client-secret
                  key: database-password
            - name: AHS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-host
            - name: AHS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-port
            - name: DATABASE_SHOULD_USE_TLS
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-should-use-tls
            - name: AHS_DB
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-name
            - name: DATABASE_CONNECTION_TIMEOUT_MILLIS
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-connection-timeout-millis
            - name: DATABASE_MAX_CLIENT_COUNT
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-max-client-count
            - name: SERVICE_USER_HOST
              value: user-service-api-service
            - name: SERVICE_USER_PORT
              value: '9000'
            - name: AHS_EXPRESS_PORT
              value: '9006'
            - name: NODE_ENV
              value: production
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
