apiVersion: apps/v1
kind: Deployment
metadata:
  name: attempt-history-service-api-deployment
  namespace: peerprep
  labels:
    app: attempt-history-service-api
spec:
  selector:
    matchLabels:
      app: attempt-history-service-api
  template:
    metadata:
      namespace: peerprep
      labels:
        app: attempt-history-service-api
    spec:
      containers:
        - name: attempt-history-service-api
          image: ghcr.io/cs3219-ay2324s1-g04/peerprep_attempt_history_service_api:demo
          ports:
            - containerPort: 9006
          env:
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: attempt-history-service-database-client-secret
                  key: database-password
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-port
            - name: DATABASE_SHOULD_USE_TLS
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-should-use-tls
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-name
            - name: DATABASE_CONNECTION_TIMEOUT_MILLIS
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-connection-timeout-millis
            - name: DATABASE_MAX_CLIENT_COUNT
              valueFrom:
                configMapKeyRef:
                  name: attempt-history-service-database-client-config-map
                  key: database-max-client-count
            - name: USER_SERVICE_HOST
              value: user-service-api-service
            - name: USER_SERVICE_PORT
              value: '9000'
            - name: API_PORT
              value: '9006'
            - name: NODE_ENV
              value: production
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 300m
