apiVersion: v1
kind: Service
metadata:
  name: attempt-history-service-api-service
  namespace: peerprep
spec:
  selector:
    app: attempt-history-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9006
      targetPort: 9006
